name: Ansible Lint
on:
  push:
    branches:
      - main

jobs:
  ansible-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: start-measurement
      - uses: actions/checkout@v4
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: ansible-lint
        uses: ansible/ansible-lint-action@c37fb7b4bda2c8cb18f4942716bae9f11b0dc9bc
        with:
          args: -x 305
          override-deps: "ansible==6.7.0

            ansible-lint==6.13.1

            "
          targets: "/github/workspace/omnia.yml

            /github/workspace/discovery_provision.yml

            /github/workspace/local_repo/local_repo.yml

            /github/workspace/server_spec_update/server_spec_update.yml

            /github/workspace/scheduler/job_based_user_access.yml

            /github/workspace/security/user_passwordless_ssh.yml

            /github/workspace/storage/nfs_sas.yml

            /github/workspace/storage/powervault.yml

            /github/workspace/telemetry/add_node_idrac.yml

            /github/workspace/tools/jupyterhub.yml

            /github/workspace/tools/kserve.yml

            /github/workspace/tools/kubeflow.yml

            /github/workspace/tools/pytorch.yml

            /github/workspace/tools/tensorflow.yml

            /github/workspace/tools/vllm.yml

            /github/workspace/utils/control_plane_cleanup.yml

            /github/workspace/utils/delete_node.yml

            /github/workspace/utils/remove_node_configuration.yml

            /github/workspace/utils/reset_cluster_configuration.yml

            /github/workspace/utils/update_user_repo.yml

            /github/workspace/utils/servicetag_host_mapping.yml

            /github/workspace/utils/software_update/software_update.yml

            /github/workspace/utils/timescaledb_utility/timescaledb_utility.yml

            /github/workspace/utils/ip_rule_assignment/ip_rule_assignment.yml

            /github/workspace/utils/nodeinfo_db/nodeinfo_db.yml

            # [optional]

            "
      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: display-results
      - name: Save Total Energy Consumption Data
        run:
          echo '${{ steps.final-measurement.outputs.data-total-json }}' > total_energy_consumption-${{
          github.run_id }}.json
      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption-${{ github.run_id }}.json
